import type {
  Trip, LoyaltyProgram, Alert, WeatherDay, TravelDocument
} from "@/types";

export const MOCK_TRIPS: Trip[] = [
  {
    id: "trip-tokyo-2026",
    name: "Tokyo & Kyoto",
    destination: "Tokyo & Kyoto",
    country: "Japan",
    countryCode: "JP",
    emoji: "🗾",
    startDate: "2026-04-18",
    endDate: "2026-04-28",
    nights: 10,
    status: "confirmed",
    planningProgress: 72,
    activitiesCount: 8,
    coverGradient: "from-[#1a3a5c] via-[#2980B9] to-[#1ABC9C]",
    budget: { total: 380000, spent: 241000, currency: "INR", breakdown: [
      { category: "Flights", amount: 152000 },
      { category: "Hotels", amount: 89000 },
      { category: "Activities", amount: 24000 },
      { category: "Food", amount: 18000 },
    ]},
    companions: [
      { id: "c1", name: "Shareef", initials: "S", avatarColor: "#C9A84C" },
      { id: "c2", name: "Rahul", initials: "R", avatarColor: "#2980B9" },
    ],
    flights: [
      {
        id: "fl-1", flightNumber: "AI 544", airline: "Air India", airlineCode: "AI",
        origin: "Chennai", originCode: "MAA", destination: "Delhi", destinationCode: "DEL",
        departureTime: "06:30", arrivalTime: "09:10", duration: "2h 20m",
        date: "2026-04-18", class: "economy", seat: "34B", terminal: "3",
        status: "on-time", pnr: "ABCD12",
      },
      {
        id: "fl-2", flightNumber: "NH 820", airline: "ANA", airlineCode: "NH",
        origin: "Delhi", originCode: "DEL", destination: "Tokyo Narita", destinationCode: "NRT",
        departureTime: "11:45", arrivalTime: "22:15", duration: "8h 45m",
        date: "2026-04-18", class: "business", seat: "22A", terminal: "3",
        status: "on-time", fareAmount: 52800, fareCurrency: "INR",
        fareDropAmount: 11600, isFareEligibleForRefund: true,
      },
      {
        id: "fl-3", flightNumber: "NH 827", airline: "ANA", airlineCode: "NH",
        origin: "Tokyo Narita", originCode: "NRT", destination: "Delhi", destinationCode: "DEL",
        departureTime: "11:00", arrivalTime: "15:30", duration: "9h 30m",
        date: "2026-04-28", class: "business", seat: "20A", terminal: "1",
        status: "on-time",
      },
    ],
    hotels: [
      {
        id: "h-1", name: "Park Hyatt Tokyo", location: "Shinjuku, Tokyo",
        checkIn: "2026-04-18", checkOut: "2026-04-24", nights: 6,
        roomType: "Deluxe Room", confirmationNumber: "JPN84921",
        loyaltyProgram: "World of Hyatt", loyaltyPoints: 4800, rating: 5,
      },
      {
        id: "h-2", name: "The Ritz-Carlton Kyoto", location: "Kyoto",
        checkIn: "2026-04-24", checkOut: "2026-04-28", nights: 4,
        roomType: "Deluxe River View", confirmationNumber: "KYO29182",
        loyaltyProgram: "Marriott Bonvoy", loyaltyPoints: 3200, rating: 5,
      },
    ],
    activities: [
      { id: "a-1", name: "Senso-ji Temple & Nakamise Market", type: "culture", emoji: "⛩️",
        date: "2026-04-19", time: "09:00", duration: "2-3 hours", location: "Asakusa, Tokyo",
        isBooked: false, rating: 4.9 },
      { id: "a-2", name: "Ichiran Ramen — Shibuya", type: "food", emoji: "🍜",
        date: "2026-04-19", time: "13:00", duration: "1 hour", location: "Shibuya, Tokyo",
        price: 1500, currency: "JPY", isBooked: true, confirmationNumber: "OT-182912" },
      { id: "a-3", name: "Meiji Shrine + Harajuku", type: "culture", emoji: "🏯",
        date: "2026-04-19", time: "15:00", duration: "2-3 hours", location: "Harajuku, Tokyo",
        isBooked: false, rating: 4.8 },
      { id: "a-4", name: "Tsukiji Outer Market Food Walk", type: "food", emoji: "🍣",
        date: "2026-04-20", time: "08:00", duration: "3 hours", location: "Tsukiji, Tokyo",
        price: 5000, currency: "JPY", isBooked: true, rating: 4.8, source: "ai" },
      { id: "a-5", name: "TeamLab Planets Digital Art", type: "culture", emoji: "🎨",
        date: "2026-04-20", time: "15:00", duration: "2 hours", location: "Toyosu, Tokyo",
        price: 3200, currency: "JPY", isBooked: true, rating: 4.9 },
      { id: "a-6", name: "Mt. Fuji Day Trip", type: "nature", emoji: "🗻",
        date: "2026-04-22", time: "07:00", duration: "Full day", location: "Fuji-Hakone",
        price: 12000, currency: "JPY", isBooked: true, rating: 4.9, source: "ai" },
      { id: "a-7", name: "Kyoto Tea Ceremony", type: "culture", emoji: "🍵",
        date: "2026-04-23", time: "14:00", duration: "1.5 hours", location: "Higashiyama, Kyoto",
        price: 8500, currency: "JPY", isBooked: true, confirmationNumber: "KTC-9281" },
      { id: "a-8", name: "Arashiyama Bamboo Grove", type: "nature", emoji: "🎋",
        date: "2026-04-24", time: "07:00", duration: "2-3 hours", location: "Arashiyama, Kyoto",
        isBooked: false, rating: 4.7 },
    ],
    requirements: [
      { type: "visa", emoji: "🗂️", title: "Japan Tourist Visa Required",
        description: "Indian passport holders need a tourist visa. Apply at Tokyo Embassy, Mumbai — minimum 3 weeks in advance.",
        severity: "warning" },
      { type: "vaccination", emoji: "💉", title: "No vaccinations required",
        description: "Japan has no mandatory vaccination requirements for Indian travelers.",
        severity: "success" },
      { type: "plug", emoji: "🔌", title: "Type A/B plug (100V)",
        description: "Japan uses Type A plugs at 100V. Carry a universal travel adapter.", severity: "info" },
      { type: "currency", emoji: "💴", title: "Japanese Yen (JPY)",
        description: "¥1 ≈ ₹0.56. Cash is widely preferred in Japan — carry sufficient Yen.", severity: "info" },
      { type: "safety", emoji: "🛡️", title: "Very safe destination",
        description: "Japan is one of the world's safest countries for international tourists.", severity: "success" },
    ],
    documents: [],
  },
  {
    id: "trip-morocco-2026",
    name: "Morocco Explorer",
    destination: "Marrakech & Fes",
    country: "Morocco",
    countryCode: "MA",
    emoji: "🇲🇦",
    startDate: "2026-06-05",
    endDate: "2026-06-15",
    nights: 10,
    status: "booked",
    planningProgress: 35,
    activitiesCount: 4,
    coverGradient: "from-[#8B4513] via-[#D4895A] to-[#F4C27A]",
    companions: [],
    flights: [], hotels: [], activities: [], requirements: [], documents: [],
  },
  {
    id: "trip-iceland-2026",
    name: "Iceland Ring Road",
    destination: "Iceland",
    country: "Iceland",
    countryCode: "IS",
    emoji: "🇮🇸",
    startDate: "2026-08-20",
    endDate: "2026-09-02",
    nights: 13,
    status: "planning",
    planningProgress: 12,
    activitiesCount: 2,
    coverGradient: "from-[#006994] via-[#1a7fa0] to-[#64B5D6]",
    companions: [],
    flights: [], hotels: [], activities: [], requirements: [], documents: [],
  },
];

export const MOCK_LOYALTY: LoyaltyProgram[] = [
  {
    id: "lp-1", name: "Air India Flying Returns", type: "airline",
    logo: "AI", logoColor: "#E84142",
    points: 84200, pendingPoints: 2400,
    tier: "Gold", tierProgress: 68, tierTarget: 100000,
    estimatedValue: 75780, currency: "INR",
    note: "Expires Dec 2026",
  },
  {
    id: "lp-2", name: "Marriott Bonvoy", type: "hotel",
    logo: "MR", logoColor: "#003580",
    points: 142800,
    tier: "Titanium Elite", tierProgress: 75, tierTarget: 75,
    estimatedValue: 128520, currency: "INR",
    note: "≈ 5 free nights",
  },
  {
    id: "lp-3", name: "IHG Rewards", type: "hotel",
    logo: "IH", logoColor: "#00447C",
    points: 31400,
    tier: "Diamond", tierProgress: 60,
    estimatedValue: 28260, currency: "INR",
    note: "≈ 2 free nights",
  },
  {
    id: "lp-4", name: "Emirates Skywards", type: "airline",
    logo: "EK", logoColor: "#00A1E0",
    points: 28100,
    tier: "Silver", tierProgress: 40,
    estimatedValue: 25290, currency: "INR",
    note: "12,000 tier miles to Gold",
  },
  {
    id: "lp-5", name: "HDFC Infinia Card", type: "credit-card",
    logo: "HD", logoColor: "#00447C",
    points: 31500,
    estimatedValue: 28350, currency: "INR",
    note: "1 pt = ₹0.90",
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: "al-1", type: "danger",
    title: "Gate Change — IndiGo 6E 781",
    message: "Gate changed to B12. Departs in 2h 40m. Allow extra walking time.",
    actionLabel: "View airport map", timestamp: new Date(),
  },
  {
    id: "al-2", type: "success",
    title: "Fare Drop — DEL→NRT",
    message: "₹52,800 → ₹41,200 (₹11,600 savings). You may be eligible for a partial refund.",
    actionLabel: "Request refund", timestamp: new Date(),
  },
  {
    id: "al-3", type: "info",
    title: "Seat Upgrade Available",
    message: "Seat 14A (window) is now available on your Apr 18 flight. Only 1 left.",
    actionLabel: "Upgrade seat", timestamp: new Date(),
  },
];

export const MOCK_WEATHER: WeatherDay[] = [
  { date: "Apr 18", emoji: "☀️", temp: 24, description: "Sunny", tip: "Cherry blossom peak — carry a light jacket for evenings" },
  { date: "Apr 19", emoji: "⛅", temp: 22, description: "Partly cloudy", tip: "Great day for outdoor temples" },
  { date: "Apr 20", emoji: "🌤️", temp: 23, description: "Mostly sunny" },
  { date: "Apr 21", emoji: "🌦️", temp: 19, description: "Light rain", tip: "Good day for TeamLab or indoor museums" },
  { date: "Apr 22", emoji: "☀️", temp: 25, description: "Perfect", tip: "Ideal day for Mt. Fuji" },
];

export const MOCK_DOCUMENTS: TravelDocument[] = [
  {
    id: "doc-1", type: "passport", name: "Indian Passport",
    description: "PP No. J7834XXX · Expires Mar 2030",
    status: "valid", expiryDate: "2030-03-15",
  },
  {
    id: "doc-2", type: "visa", name: "Japan Tourist Visa",
    description: "Apply at Tokyo Embassy, Mumbai",
    status: "pending",
  },
  {
    id: "doc-3", type: "insurance", name: "Travel Insurance",
    description: "ICICI Lombard · Apr–May 2026",
    status: "valid", expiryDate: "2026-05-31",
  },
  {
    id: "doc-4", type: "ticket", name: "ANA NH820 E-ticket",
    description: "DEL→NRT · Apr 18 · Seat 22A",
    status: "valid", tripId: "trip-tokyo-2026",
  },
  {
    id: "doc-5", type: "hotel", name: "Park Hyatt Tokyo Conf.",
    description: "Apr 18–24 · #JPN84921",
    status: "valid", tripId: "trip-tokyo-2026",
  },
];

export const QUICK_PROMPTS = [
  { label: "Plan a 7-day Japan trip", prompt: "Plan a 7-day luxury trip to Japan in April for an Indian traveler from Chennai. Include flights, hotels, and must-see experiences." },
  { label: "Flight alternatives", prompt: "If my Tokyo flight NH820 gets cancelled, what are the best alternative flights from Delhi to Tokyo?" },
  { label: "Hidden gems in Kyoto", prompt: "What are the hidden gems and off-the-beaten-path experiences in Kyoto that a luxury traveler would love?" },
  { label: "Best restaurants Shinjuku", prompt: "What are the best luxury and high-end restaurants in Shinjuku, Tokyo? Include cuisine type and reservation tips." },
  { label: "Visa for Japan from India", prompt: "What is the Japan tourist visa process for Indian passport holders? What documents are needed and how long does it take?" },
  { label: "Morocco itinerary", prompt: "Create a 10-day Morocco itinerary covering Marrakech, Fes, and the Sahara Desert. I prefer boutique riads and authentic experiences." },
];
